#
# Fun LEDs
set_property IOSTANDARD LVCMOS25 [get_ports LED0]
set_property IOSTANDARD LVCMOS25 [get_ports LED1]
set_property IOSTANDARD LVCMOS25 [get_ports LED2]
set_property IOSTANDARD LVCMOS25 [get_ports LED3]

#
# For I2C IP Core testing
set_property PULLUP true [get_ports I2C_scl_io]
set_property PULLUP true [get_ports I2C_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_sda_io]


#
# AMACv2 Digital IO
set_property IOSTANDARD LVCMOS25 [get_ports RO_PG_O]
set_property IOSTANDARD LVCMOS25 [get_ports OFout]
set_property IOSTANDARD LVCMOS25 [get_ports GPO]
set_property IOSTANDARD LVCMOS25 [get_ports RESETB]
set_property IOSTANDARD LVCMOS25 [get_ports DCDCen]
set_property IOSTANDARD LVCMOS25 [get_ports {ID[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ID[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ID[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ID[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ID[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports LDx0en]
set_property IOSTANDARD LVCMOS25 [get_ports LDx1en]
set_property IOSTANDARD LVCMOS25 [get_ports LDx2en]
set_property IOSTANDARD LVCMOS25 [get_ports LDy0en]
set_property IOSTANDARD LVCMOS25 [get_ports LDy1en]
set_property IOSTANDARD LVCMOS25 [get_ports LDy2en]
set_property IOSTANDARD LVCMOS25 [get_ports SSSHx]
set_property IOSTANDARD LVCMOS25 [get_ports SSSHy]
set_property IOSTANDARD LVCMOS25 [get_ports HrstBx]
set_property IOSTANDARD LVCMOS25 [get_ports HrstBy]
set_property IOSTANDARD LVCMOS25 [get_ports OFin]
set_property IOSTANDARD LVCMOS25 [get_ports DCDCadj]
set_property IOSTANDARD LVCMOS25 [get_ports GPI]
set_property IOSTANDARD LVCMOS25 [get_ports LAM]
set_property IOSTANDARD LVCMOS25 [get_ports PGOOD]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_CMD_IN_P]
set_property DIFF_TERM TRUE [get_ports FPGA_CMD_IN_P]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_CMD_OUT_P]
set_property DIFF_TERM TRUE [get_ports FPGA_CMD_OUT_N]
set_property DIFF_TERM TRUE [get_ports FPGA_CMD_OUT_P]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_HVOSC0]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_HVOSC1]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_HVOSC2]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_HVOSC3]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_CLKOUT]

#
# Testboard Control
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports SDI]
set_property IOSTANDARD LVCMOS25 [get_ports SDO]
set_property IOSTANDARD LVCMOS25 [get_ports DPOT_CS0]
set_property IOSTANDARD LVCMOS25 [get_ports DPOT_CS1]
set_property IOSTANDARD LVCMOS25 [get_ports DPOT_CS2]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_CS0]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_CS1]
set_property IOSTANDARD LVCMOS25 [get_ports ADC_CS0]
set_property IOSTANDARD LVCMOS25 [get_ports ADC_CS1]
set_property IOSTANDARD LVCMOS25 [get_ports ADC_CS2]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_ADC_CNV]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_DVDD]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_DCDC]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_HV]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_HI]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_5]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_3V3]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports LD_EN_1V8]

